import { useState } from 'react';
import { BadgeCheck, Heart, MapPin, ShoppingBag, Star } from 'lucide-react';
import { categories, deals, recommendations, services } from '../../data/home';

const iconMap = { 'Shopping Bag': ShoppingBag, 'Hard Hat': ShoppingBag, 'Calendar Check': ShoppingBag, Briefcase: ShoppingBag, House: ShoppingBag, Car: ShoppingBag, Store: ShoppingBag, Users: ShoppingBag } as Record<string, typeof ShoppingBag>;

export function CategoryGrid() { return <section aria-label="Quick category shortcuts" className="relative z-20 -mt-12 amazon-container"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{categories.map(([icon, title, detail]) => { const Icon = iconMap[icon]; return <a href="#" key={title} className="group rounded-xl border-2 border-transparent bg-white p-4 text-center shadow-md transition hover:-translate-y-1 hover:border-honey hover:shadow-xl"><div className="mx-auto mb-2 flex h-12 w-12 items-center justify-center rounded-lg bg-softyellow transition group-hover:bg-honey"><Icon className="h-6 w-6 text-charcoal" /></div><span className="block text-xs font-semibold leading-tight">{title}</span><span className="mt-0.5 block text-[10px] text-mutedgray">{detail}</span></a>; })}</div></section>; }

export function FeaturePanels() { const panels = [['Deals of the Day', 'Limited-time savings', 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&q=80&auto=format&fit=crop'], ['Services Near You', 'Trusted local pros', 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80&auto=format&fit=crop'], ['Popular Local Businesses', 'Community favorites', 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400&q=80&auto=format&fit=crop'], ['Start Selling on AsBeez', 'Grow your reach', 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&q=80&auto=format&fit=crop']] as const; return <section aria-label="Marketplace highlights" className="amazon-container py-10 sm:py-14"><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{panels.map(([title, copy, image]) => <article key={title} className="overflow-hidden rounded-xl bg-white shadow-md transition hover:shadow-xl"><div className="p-4 pb-2"><h3 className="text-lg font-bold">{title}</h3><p className="text-xs text-mutedgray">{copy}</p></div><div className="grid grid-cols-2 gap-2 px-4">{[image, image, image, image].map((source, index) => <img key={index} src={source} alt="" className="h-24 w-full rounded-lg object-cover" loading="lazy" />)}</div><a href="#" className="block px-4 py-3 text-sm font-semibold text-amber hover:text-charcoal">See More →</a></article>)}</div></section>; }

export function DealsRail() { const [cart, setCart] = useState(3); return <section aria-label="Today's deals" className="amazon-container pb-10 sm:pb-14"><div className="mb-5"><h2 className="text-xl font-extrabold sm:text-2xl">Today's Deals</h2><p className="text-sm text-mutedgray">Grab them before they're gone</p></div><div className="flex gap-4 overflow-x-auto pb-2 scrollbar-hide">{deals.map(([title, price, oldPrice, discount, reviews, image]) => <article key={title} className="group relative w-52 shrink-0 overflow-hidden rounded-xl bg-white shadow-md transition hover:shadow-xl sm:w-56"><span className="absolute left-2 top-2 z-10 rounded bg-red-600 px-2 py-1 text-xs font-bold text-white">{discount}</span><button aria-label="Add to wishlist" className="absolute right-2 top-2 z-10 rounded-full bg-white/90 p-1.5"><Heart className="h-4 w-4 text-gray-400" /></button><img src={image} alt={title} className="h-44 w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="p-3"><h3 className="mb-1 line-clamp-2 text-sm font-semibold">{title}</h3><div className="mb-1 flex items-center gap-1 text-honey"><Star className="h-3.5 w-3.5 fill-honey" /><span className="text-xs text-mutedgray">({reviews})</span></div><div className="mb-1 flex items-baseline gap-2"><span className="text-lg font-bold">{price}</span><span className="text-sm text-mutedgray line-through">{oldPrice}</span></div><p className="mb-2 text-xs font-medium text-successgreen">Free delivery</p><button onClick={() => setCart((value) => value + 1)} className="w-full rounded-lg bg-honey py-2 text-sm font-bold text-charcoal hover:bg-amber">Add to Cart ({cart})</button></div></article>)}</div></section>; }

export function ServicesGrid() { return <section aria-label="Popular services" className="amazon-container pb-10 sm:pb-14"><div className="mb-5"><h2 className="text-xl font-extrabold sm:text-2xl">Popular Services</h2><p className="text-sm text-mutedgray">Trusted providers in your community</p></div><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">{services.map(([title, vendor, rating, reviews, price, distance, image]) => <article key={title} className="group overflow-hidden rounded-xl bg-white shadow-md transition hover:shadow-xl"><img src={image} alt={title} className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="p-4"><div className="mb-2 flex items-center justify-between gap-2"><h3 className="text-lg font-bold">{title}</h3><span className="flex items-center gap-1 rounded-full bg-successgreen/10 px-2 py-1 text-xs font-semibold text-successgreen"><BadgeCheck className="h-3.5 w-3.5" /> Verified</span></div><p className="mb-2 text-sm text-mutedgray">by {vendor}</p><div className="mb-2 flex items-center gap-1 text-honey"><Star className="h-4 w-4 fill-honey" /><span className="text-sm font-semibold text-charcoal">{rating}</span><span className="text-xs text-mutedgray">({reviews})</span></div><div className="mb-3 flex items-center justify-between"><span className="text-lg font-bold">{price}</span><span className="flex items-center gap-1 text-xs text-mutedgray"><MapPin className="h-3.5 w-3.5" /> {distance}</span></div><button className="w-full rounded-lg bg-charcoal py-2.5 text-sm font-bold text-white hover:bg-honey hover:text-charcoal">View Service</button></div></article>)}</div></section>; }

export function Recommendations() { return <section aria-label="Recommended products" className="amazon-container py-10 sm:py-14"><div className="mb-5"><h2 className="text-xl font-extrabold sm:text-2xl">Recommended for You</h2><p className="text-sm text-mutedgray">Based on your browsing and community trends</p></div><div className="grid grid-cols-2 gap-4 md:grid-cols-3 lg:grid-cols-4">{recommendations.map(([title, price, status, image]) => <article key={title} className="group overflow-hidden rounded-xl bg-white shadow-md transition hover:shadow-xl"><img src={image} alt={title} className="h-48 w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /><div className="p-3"><h3 className="mb-1 line-clamp-2 text-sm font-semibold">{title}</h3><div className="mb-1 flex items-center gap-1 text-honey"><Star className="h-3.5 w-3.5 fill-honey" /><span className="text-xs text-mutedgray">4.8</span></div><span className="text-lg font-bold">{price}</span><p className="mb-2 text-xs font-medium text-successgreen">{status}</p><button className="w-full rounded-lg bg-honey py-2 text-sm font-bold text-charcoal hover:bg-amber">Add to Cart</button></div></article>)}</div></section>; }
