import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight } from 'lucide-react';

const slides = [
  { eyebrow: 'Welcome to the Hive', title: 'Everything You Need, All in One Hive', copy: 'Discover products, services, professionals, and local opportunities—all in one trusted marketplace.', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1800&q=80&auto=format&fit=crop', action: 'Start Exploring' },
  { eyebrow: 'Trusted Experts', title: 'Trusted Local Professionals', copy: 'Find experienced service providers in your area, verified and reviewed by your community.', image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1800&q=80&auto=format&fit=crop', action: 'Browse Services' },
  { eyebrow: 'Grow With Us', title: 'Grow Your Business with AsBeez', copy: 'Reach more customers and manage your marketplace presence with powerful tools built for local sellers.', image: 'https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1800&q=80&auto=format&fit=crop', action: 'Join AsBeez' },
];

export function Hero() {
  const [active, setActive] = useState(0);
  useEffect(() => { const timer = window.setInterval(() => setActive((current) => (current + 1) % slides.length), 6000); return () => window.clearInterval(timer); }, []);
  const slide = slides[active];
  return <section aria-label="Featured promotions" className="relative h-[320px] overflow-hidden sm:h-[400px] lg:h-[480px]"><img src={slide.image} alt={slide.title} className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-charcoal/85 via-charcoal/60 to-transparent" /><div className="relative z-10 flex h-full items-center"><div className="amazon-container"><div className="max-w-lg px-3 sm:px-4 lg:px-3"><span className="mb-4 inline-block rounded-full bg-honey px-3 py-1 text-xs font-bold uppercase tracking-wider text-charcoal">{slide.eyebrow}</span><h1 className="mb-4 text-3xl font-extrabold leading-tight text-white sm:text-4xl lg:text-5xl">{slide.title}</h1><p className="mb-6 text-base text-gray-200 sm:text-lg">{slide.copy}</p><a href="#" className="inline-block rounded-lg bg-honey px-6 py-3 font-bold text-charcoal shadow-lg transition hover:bg-amber">{slide.action}</a></div></div></div><button aria-label="Previous slide" onClick={() => setActive((active - 1 + slides.length) % slides.length)} className="absolute left-3 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/20 p-2.5 text-white backdrop-blur-sm hover:bg-white/40"><ChevronLeft /></button><button aria-label="Next slide" onClick={() => setActive((active + 1) % slides.length)} className="absolute right-3 top-1/2 z-20 -translate-y-1/2 rounded-full bg-white/20 p-2.5 text-white backdrop-blur-sm hover:bg-white/40"><ChevronRight /></button><div className="absolute bottom-4 left-1/2 z-20 flex -translate-x-1/2 gap-2">{slides.map((_, index) => <button key={index} aria-label={`Go to slide ${index + 1}`} onClick={() => setActive(index)} className={`h-3 w-3 rounded-full ${index === active ? 'bg-honey' : 'bg-white/50'}`} />)}</div></section>;
}
