import { useState, type FormEvent } from 'react';
import { CheckCircle2, HeartHandshake, LockKeyhole, Mail, Search, ShieldCheck } from 'lucide-react';

export function SellerBanner() {
    return <section aria-label="Sell on AsBeez" className="honeycomb-bg border-y border-honey/20"><div className="amazon-container py-12 sm:py-16"><div className="rounded-2xl bg-charcoal p-8 text-center sm:p-12"><h2 className="mb-4 text-2xl font-extrabold text-white sm:text-3xl lg:text-4xl">Have Something to Offer?</h2><p className="mx-auto mb-8 max-w-2xl text-base text-gray-300 sm:text-lg">Sell products, advertise your services, or grow your local business. Join sellers and service providers reaching customers in their community.</p><div className="flex flex-wrap justify-center gap-4"><a href="#" className="rounded-lg bg-honey px-8 py-3.5 font-bold text-charcoal shadow-lg hover:bg-amber">Create Your Listing</a><a href="#" className="rounded-lg border border-white/20 bg-white/10 px-8 py-3.5 font-bold text-white hover:bg-white/20">Learn How It Works</a></div></div></div></section>;
}

export function HowItWorks() {
    const steps = [[Search, 'Search or Browse', 'Explore products, services, and local opportunities.'], [HeartHandshake, 'Compare and Connect', 'Check ratings, compare options, and connect with providers.'], [CheckCircle2, 'Buy, Book, or Hire', 'Complete your transaction securely and confidently.']] as const;
    return <section aria-label="How AsBeez works" className="border-y border-gray-100 bg-white"><div className="amazon-container py-12 sm:py-16"><div className="mb-10 text-center"><h2 className="mb-2 text-xl font-extrabold sm:text-2xl">How AsBeez Works</h2><p className="mx-auto max-w-lg text-sm text-mutedgray">Your community marketplace made simple.</p></div><div className="grid grid-cols-1 gap-8 md:grid-cols-3">{steps.map(([Icon, title, copy], index) => <div key={title} className="relative text-center"><div className="mx-auto mb-4 flex h-20 w-20 items-center justify-center rounded-2xl bg-honey shadow-lg"><Icon className="h-9 w-9 text-charcoal" /></div><span className="mb-3 inline-block rounded-full bg-honey px-3 py-1 text-xs font-bold text-charcoal">Step {index + 1}</span><h3 className="mb-2 text-lg font-bold">{title}</h3><p className="mx-auto max-w-xs text-sm text-mutedgray">{copy}</p></div>)}</div></div></section>;
}

export function TrustGrid() {
    const trust = [[ShieldCheck, 'Verified Sellers and Providers', 'Vetted marketplace participants and clear community signals.'], [LockKeyhole, 'Secure Transactions', 'Protected payments, private data, and controlled workflows.'], [HeartHandshake, 'Local Community Connections', 'Support local businesses and meaningful marketplace relationships.'], [Mail, 'Responsive Customer Support', 'Help before, during, and after every transaction.'] ] as const;
    return <section aria-label="Trust and benefits" className="amazon-container py-12 sm:py-16"><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-4">{trust.map(([Icon, title, copy]) => <article key={title} className="rounded-xl border-t-4 border-honey bg-white p-6 shadow-md"><div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-softyellow"><Icon className="h-6 w-6 text-charcoal" /></div><h3 className="mb-2 font-bold">{title}</h3><p className="text-sm text-mutedgray">{copy}</p></article>)}</div></section>;
}

export function Newsletter() {
    const [email, setEmail] = useState('');
    const [message, setMessage] = useState('');
    function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!email.includes('@')) { setMessage('Please enter a valid email address.'); return; } setMessage('Thanks for joining the hive.'); setEmail(''); }
    return <section aria-label="Newsletter signup" className="honeycomb-bg border-y border-honey/20"><div className="amazon-container py-12 text-center sm:py-16"><Mail className="mx-auto mb-4 h-12 w-12 text-amber" /><h2 className="mb-3 text-2xl font-extrabold">Get the Latest Buzz</h2><p className="mx-auto mb-6 max-w-md text-sm text-mutedgray">Subscribe for deals, new providers, and community updates.</p><form onSubmit={submit} className="mx-auto flex max-w-md flex-col gap-3 sm:flex-row"><label htmlFor="newsletter-email" className="sr-only">Email address</label><input id="newsletter-email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="Enter your email address" className="min-w-0 flex-1 rounded-lg border-2 border-gray-200 px-4 py-3 text-sm outline-none focus:border-honey" /><button className="rounded-lg bg-honey px-6 py-3 font-bold text-charcoal hover:bg-amber">Join the Hive</button></form>{message && <p className="mt-3 text-sm font-medium text-successgreen" role="status">{message}</p>}<p className="mt-3 text-xs text-mutedgray">We respect your privacy. Unsubscribe anytime.</p></div></section>;
}

export function Footer() {
    return <footer className="mt-8 bg-charcoal py-12 text-white"><div className="amazon-container"><div className="grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-5"><FooterGroup title="Get to Know AsBeez" items={['About Us', 'Careers', 'Press', 'Community Impact']} /><FooterGroup title="Shop and Explore" items={['Products', 'Local Services', 'Professionals', 'Jobs', 'Real Estate']} /><FooterGroup title="Sell and Grow" items={['Sell on AsBeez', 'Business Tools', 'Advertising', 'Seller Resources']} /><FooterGroup title="Customer Support" items={['Help Center', 'Contact Us', 'Returns', 'Report an Issue']} /><FooterGroup title="Legal and Policies" items={['Privacy Policy', 'Terms of Service', 'Accessibility', 'Trust & Safety']} /></div><div className="mt-10 border-t border-white/10 pt-8 text-center"><div className="text-xl font-extrabold"><span className="text-honey">As</span>Beez</div><p className="mt-3 text-sm text-gray-400">Find it. Book it. Get it done.</p><p className="mt-6 text-xs text-gray-500">© 2025 AsBeez Marketplace. All rights reserved.</p></div></div></footer>;
}

function FooterGroup({ title, items }: { title: string; items: string[] }) { return <div><h3 className="mb-4 text-sm font-bold uppercase tracking-wider text-honey">{title}</h3><ul className="space-y-2 text-sm text-gray-300">{items.map((item) => <li key={item}><a href="#" className="hover:text-honey">{item}</a></li>)}</ul></div>; }
