<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\NavLink;
use App\Models\NotificationChannel;
use App\Models\NotificationTopic;
use App\Models\PolicyType;
use App\Models\SettingDefinition;
use App\Models\SocialPlatform;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

/**
 * Spanish translations for the admin-curated registries.
 *
 * Written as data rather than edited into the models: the same rows are what
 * the admin translation screens write, so seeding and editing share one path.
 * Anything missing here simply falls back to English, which is why partial
 * coverage is safe.
 */
class SpanishContentSeeder extends Seeder
{
    use WithoutModelEvents;

    private const LOCALE = 'es';

    public function run(): void
    {
        $count = 0;

        $count += $this->translate(Category::class, 'slug', 'name', [
            // Travel: the fourteen departments and their leaves.
            'travel-resorts' => 'Resorts',
            'travel-boutique-hotels' => 'Hoteles boutique y de diseño',
            'travel-bnb' => 'Casas de huéspedes con desayuno',
            'travel-holiday-homes' => 'Casas de vacaciones',
            'travel-rental-apartments' => 'Apartamentos turísticos',
            'travel-cabins' => 'Cabañas y chalés',
            'travel-villas' => 'Villas',
            'travel-flights-standard' => 'Ida y vuelta',
            'travel-flights-multi-city' => 'Multidestino',
            'travel-flights-premium' => 'Business y primera clase',
            'travel-flights-charter' => 'Chárter y vuelos privados',
            'travel-car-airport' => 'Recogida en aeropuerto',
            'travel-car-city' => 'Alquiler urbano',
            'travel-car-campervan' => 'Campers y autocaravanas',
            'travel-car-chauffeur' => 'Con conductor y VTC',
            'travel-cruise-ocean' => 'Cruceros oceánicos',
            'travel-cruise-river' => 'Cruceros fluviales',
            'travel-cruise-expedition' => 'Expedición y aventura',
            'travel-cruise-luxury' => 'Cruceros de lujo',
            'travel-day-tours' => 'Excursiones de un día',
            'travel-attractions' => 'Atracciones y entradas',
            'travel-adventure' => 'Aventura y aire libre',
            'travel-food-culture' => 'Gastronomía y cultura',
            'travel-guided-tours' => 'Circuitos guiados de varios días',
            'travel-packages' => 'Paquetes de viaje',
            'travel-package-flight-hotel' => 'Vuelo y hotel',
            'travel-package-all-inclusive' => 'Todo incluido',
            'travel-package-honeymoon' => 'Luna de miel y escapadas',
            'travel-package-family' => 'Paquetes familiares',
            'travel-transfer-private' => 'Traslados privados',
            'travel-transfer-shuttle' => 'Lanzaderas compartidas',
            'travel-transfer-taxi' => 'Taxi y VTC',
            'travel-rail-bus' => 'Tren y autobús',
            'travel-rail' => 'Billetes y abonos de tren',
            'travel-coach' => 'Autobús interurbano',
            'travel-scenic-rail' => 'Trenes panorámicos y nocturnos',
            'travel-advisors-leisure' => 'Asesores de viajes de ocio',
            'travel-advisors-destination' => 'Especialistas por destino',
            'travel-advisors-luxury' => 'Asesores de viajes de lujo',
            'travel-agencies' => 'Agencias',
            'travel-corporate' => 'Viajes corporativos',
            'travel-corporate-booking' => 'Reservas de viajes de negocios',
            'travel-corporate-policy' => 'Política de viajes y gastos',
            'travel-corporate-mice' => 'Reuniones y congresos',
            'travel-group' => 'Viajes en grupo',
            'travel-group-tours' => 'Grupos organizados',
            'travel-group-student' => 'Viajes escolares y de estudiantes',
            'travel-group-weddings' => 'Bodas y celebraciones',
            'travel-group-affinity' => 'Grupos religiosos y de afinidad',
            'travel-protection' => 'Seguro de viaje',
            'travel-protection-trip' => 'Protección del viaje',
            'travel-protection-medical' => 'Asistencia médica y evacuación',
            'travel-protection-baggage' => 'Equipaje y retrasos',
            'travel-documents' => 'Visados y documentación de viaje',
            'travel-visa' => 'Solicitudes de visado',
            'travel-passport' => 'Gestión de pasaportes',
            'travel-eta' => 'Autorizaciones de viaje',
            'travel-doc-translation' => 'Traducción y legalización',
            // Insurance: the fourteen departments and their leaves.
            'insurance-term-life' => 'Vida temporal',
            'insurance-whole-life' => 'Vida entera',
            'insurance-universal-life' => 'Vida universal',
            'insurance-final-expense' => 'Gastos de sepelio',
            'insurance-health-individual' => 'Planes individuales y familiares',
            'insurance-health-short-term' => 'Cobertura médica temporal',
            'insurance-dental-vision' => 'Dental y óptica',
            'insurance-critical-illness' => 'Enfermedades graves',
            'insurance-medicare' => 'Soluciones Medicare',
            'insurance-medicare-advantage' => 'Medicare Advantage',
            'insurance-medicare-supplement' => 'Medicare complementario',
            'insurance-medicare-part-d' => 'Parte D de recetas',
            'insurance-disability' => 'Seguros de incapacidad',
            'insurance-disability-short' => 'Incapacidad temporal',
            'insurance-disability-long' => 'Incapacidad de larga duración',
            'insurance-disability-business' => 'Gastos fijos del negocio',
            'insurance-long-term-care' => 'Seguros de dependencia',
            'insurance-ltc-traditional' => 'Dependencia tradicional',
            'insurance-ltc-hybrid' => 'Vida y dependencia combinadas',
            'insurance-ltc-home-care' => 'Cobertura de cuidados en casa',
            'insurance-annuities' => 'Rentas vitalicias',
            'insurance-annuity-fixed' => 'Renta fija',
            'insurance-annuity-indexed' => 'Renta indexada',
            'insurance-annuity-variable' => 'Renta variable',
            'insurance-annuity-immediate' => 'Renta inmediata',
            'insurance-auto-personal' => 'Automóvil particular',
            'insurance-auto-motorcycle' => 'Motos y vehículos deportivos',
            'insurance-auto-commercial' => 'Vehículos comerciales',
            'insurance-auto-classic' => 'Clásicos y de colección',
            'insurance-homeowners' => 'Propietarios de vivienda',
            'insurance-renters' => 'Inquilinos',
            'insurance-condo' => 'Comunidades y pisos',
            'insurance-landlord' => 'Arrendadores y vivienda en alquiler',
            'insurance-flood' => 'Inundación y catástrofes',
            'insurance-travel-cancellation' => 'Cancelación de viaje',
            'insurance-travel-medical' => 'Asistencia médica en viaje',
            'insurance-travel-annual' => 'Anual multiviaje',
            'insurance-general-liability' => 'Responsabilidad civil general',
            'insurance-professional-liability' => 'Responsabilidad civil profesional',
            'insurance-commercial-property' => 'Inmuebles comerciales',
            'insurance-workers-comp' => 'Accidentes de trabajo',
            'insurance-cyber' => 'Ciberriesgos',
            'insurance-group-benefits' => 'Colectivos y beneficios para empleados',
            'insurance-group-health' => 'Salud colectiva',
            'insurance-group-life' => 'Vida e incapacidad colectiva',
            'insurance-group-retirement' => 'Planes de jubilación',
            'insurance-voluntary-benefits' => 'Beneficios voluntarios',
            'insurance-specialty' => 'Seguros especializados',
            'insurance-event' => 'Eventos y responsabilidad civil',
            'insurance-marine' => 'Náutico y embarcaciones',
            'insurance-umbrella' => 'Responsabilidad civil ampliada',
            'insurance-identity-theft' => 'Robo de identidad',
            'insurance-independent-agents' => 'Agentes independientes',
            'insurance-captive-agents' => 'Agentes exclusivos',
            'insurance-agencies' => 'Agencias y correduría',
            'insurance-benefits-consultants' => 'Consultores de beneficios',
            'insurance-education' => 'Recursos formativos y análisis de necesidades',
            'insurance-guides' => 'Guías de cobertura',
            'insurance-needs-analysis' => 'Herramientas de análisis de necesidades',
            'insurance-quote-comparison' => 'Comparador de presupuestos',
            'insurance-glossary' => 'Glosario y preguntas frecuentes',
            // Automotive: the sixteen departments and their leaves.
            'vehicles-new' => 'Vehículos nuevos',
            'vehicles-new-cars' => 'Turismos y berlinas',
            'vehicles-new-suvs' => 'SUV y todocamino',
            'vehicles-new-trucks' => 'Camionetas y pick-ups',
            'vehicles-new-electric' => 'Eléctricos e híbridos',
            'vehicles-used-cars' => 'Turismos y berlinas de ocasión',
            'vehicles-used-suvs' => 'SUV de ocasión',
            'vehicles-used-trucks' => 'Camionetas de ocasión',
            'vehicles-used-vans' => 'Furgonetas y monovolúmenes',
            'vehicles-certified' => 'Vehículos certificados',
            'vehicles-cpo-manufacturer' => 'Certificados por el fabricante',
            'vehicles-cpo-dealer' => 'Certificados por el concesionario',
            'vehicles-private-party' => 'Venta entre particulares',
            'vehicles-owner-listings' => 'Anuncios de particulares',
            'vehicles-project-salvage' => 'Proyectos y siniestrados',
            'vehicles-classic' => 'Clásicos y de colección',
            'vehicles-motorcycles' => 'Motos y vehículos deportivos',
            'powersports-motorcycles' => 'Motocicletas',
            'powersports-scooters' => 'Scooters y ciclomotores',
            'powersports-atv' => 'Quads y buggies',
            'powersports-snow-water' => 'Motos de nieve y acuáticas',
            'vehicles-recreational' => 'Autocaravanas y caravanas',
            'rv-motorhomes' => 'Autocaravanas',
            'rv-travel-trailers' => 'Caravanas',
            'rv-campers' => 'Campers y plegables',
            'vehicles-commercial' => 'Vehículos comerciales',
            'commercial-box-trucks' => 'Camiones y furgones',
            'commercial-heavy-trucks' => 'Camiones pesados',
            'commercial-trailers' => 'Remolques',
            'commercial-equipment' => 'Maquinaria de obra y agrícola',
            'vehicles-marine' => 'Barcos y embarcaciones',
            'marine-powerboats' => 'Embarcaciones a motor',
            'marine-sailboats' => 'Veleros',
            'marine-pwc' => 'Motos acuáticas',
            'marine-parts' => 'Piezas náuticas y remolques',
            'auto-parts-engine' => 'Motor y transmisión',
            'auto-parts-body' => 'Carrocería y exterior',
            'auto-parts-interior' => 'Interior y electrónica',
            'auto-parts-performance' => 'Rendimiento y tuning',
            'auto-inspections' => 'Inspecciones e historial del vehículo',
            'auto-prepurchase-inspection' => 'Inspección previa a la compra',
            'auto-history-reports' => 'Informes de historial',
            'auto-emissions-testing' => 'Emisiones y seguridad',
            'auto-general-repair' => 'Reparación general',
            'auto-maintenance' => 'Mantenimiento programado',
            'auto-body-collision' => 'Chapa y pintura',
            'auto-tyre-service' => 'Servicio de neumáticos',
            'auto-mobile-mechanics' => 'Mecánicos a domicilio',
            'auto-detail-interior' => 'Limpieza de interiores',
            'auto-detail-exterior' => 'Exterior y pulido',
            'auto-detail-coating' => 'Cerámicos y vinilos',
            'auto-car-wash' => 'Lavado de coches',
            'auto-towing' => 'Grúa y asistencia en carretera',
            'auto-tow-service' => 'Servicio de grúa',
            'auto-jump-lockout' => 'Arranque y apertura',
            'auto-roadside-tyre-fuel' => 'Cambio de rueda y combustible',
            'auto-financing' => 'Financiación de vehículos',
            'auto-loans' => 'Préstamos para vehículos',
            'auto-leasing' => 'Renting y leasing',
            'auto-trade-in' => 'Tasación y entrega a cuenta',
            'auto-warranties' => 'Garantías y productos de protección',
            'auto-extended-warranty' => 'Garantía extendida',
            'auto-service-contracts' => 'Contratos de mantenimiento',
            'auto-gap-protection' => 'Seguros GAP y protección',
            'auto-rentals' => 'Alquiler de coches local',
            'auto-rental-daily' => 'Alquiler por días y semanas',
            'auto-rental-truck' => 'Alquiler de furgonetas y camiones',
            'auto-rental-p2p' => 'Alquiler entre particulares',
            'auto-rental-luxury' => 'Lujo y vehículos especiales',
            // Real Estate: the fourteen departments and their leaves.
            'property-houses' => 'Casas',
            'property-condos' => 'Pisos y apartamentos',
            'property-townhouses' => 'Adosados',
            'property-multi-family' => 'Plurifamiliar',
            'property-office-sale' => 'Edificios de oficinas',
            'property-retail-sale' => 'Locales comerciales',
            'property-industrial-sale' => 'Naves e industrial',
            'property-hospitality' => 'Hostelería y ocio',
            'property-new-developments' => 'Obra nueva',
            'property-preconstruction' => 'Sobre plano',
            'property-show-homes' => 'Pisos piloto',
            'property-communities' => 'Urbanizaciones planificadas',
            'property-land' => 'Terrenos y parcelas',
            'property-residential-lots' => 'Parcelas residenciales',
            'property-commercial-land' => 'Suelo comercial',
            'property-agricultural-land' => 'Suelo agrícola',
            'property-recreational-land' => 'Suelo recreativo',
            'property-house-rentals' => 'Casas en alquiler',
            'property-apartment-rentals' => 'Pisos en alquiler',
            'property-short-term' => 'Alquiler de corta duración',
            'property-commercial-lease' => 'Alquiler comercial',
            'property-office-lease' => 'Oficinas en alquiler',
            'property-retail-lease' => 'Locales en alquiler',
            'property-industrial-lease' => 'Naves en alquiler',
            'property-coworking' => 'Coworking y espacios flexibles',
            'property-vacation-investment' => 'Segunda residencia e inversión',
            'property-vacation-homes' => 'Casas de vacaciones',
            'property-rental-investment' => 'Inversión en alquiler',
            'property-timeshare' => 'Multipropiedad y tiempo compartido',
            'property-overseas' => 'Inmuebles en el extranjero',
            'property-agents' => 'Agentes y corredores inmobiliarios',
            'property-buyer-agents' => 'Agentes del comprador',
            'property-listing-agents' => 'Agentes del vendedor',
            'property-commercial-brokers' => 'Corredores comerciales',
            'property-brokerages' => 'Agencias inmobiliarias',
            'property-mortgage' => 'Hipotecas y financiación',
            'property-mortgage-brokers' => 'Intermediarios hipotecarios',
            'property-lenders' => 'Entidades prestamistas',
            'property-refinancing' => 'Refinanciación',
            'property-preapproval' => 'Preaprobación',
            'property-residential-management' => 'Gestión de vivienda',
            'property-commercial-management' => 'Gestión de inmuebles comerciales',
            'property-tenant-placement' => 'Búsqueda de inquilinos',
            'property-maintenance' => 'Coordinación de mantenimiento',
            'property-inspection' => 'Inspección de viviendas',
            'property-prepurchase-inspection' => 'Inspección previa a la compra',
            'property-specialty-inspection' => 'Inspecciones especializadas',
            'property-energy-audit' => 'Auditorías energéticas',
            'property-appraisal' => 'Tasación y valoración',
            'property-residential-appraisal' => 'Tasación de vivienda',
            'property-commercial-appraisal' => 'Tasación comercial',
            'property-market-analysis' => 'Análisis de mercado',
            'property-escrow-title' => 'Depósito, titularidad y cierre',
            'property-escrow' => 'Servicios de depósito',
            'property-title' => 'Estudio y seguro de título',
            'property-closing' => 'Cierre y liquidación',
            'property-notary' => 'Servicios notariales',
            'property-legal' => 'Servicios jurídicos inmobiliarios',
            'property-conveyancing' => 'Tramitación de compraventa',
            'property-landlord-tenant' => 'Derecho de arrendamiento',
            'property-zoning' => 'Urbanismo y usos del suelo',
            'property-disputes' => 'Conflictos inmobiliarios',
            // Professional Services: the three groups and their new rows.
            'services-personal' => 'Personal y estilo de vida',
            'hr-recruiting' => 'Recursos humanos y selección',
            'it-support' => 'Soporte informático y ciberseguridad',
            'handyman-repairs' => 'Manitas y reparaciones',
            'construction-renovation' => 'Construcción y reformas',
            'fitness-coaching' => 'Fitness y entrenamiento personal',
            'senior-care' => 'Cuidado de mayores',
            'personal-assistance' => 'Asistencia personal',
            'event-planning' => 'Organización de eventos',
            // Digital Products: the thirteen departments and their leaves.
            'ebooks-general' => 'Ficción y no ficción',
            'ebooks-guides' => 'Guías y manuales',
            'ebooks-magazines' => 'Revistas y fanzines',
            'ebooks-comics' => 'Cómics y novelas gráficas',
            'courses-video' => 'Cursos en vídeo',
            'courses-workbooks' => 'Cuadernos y fichas',
            'courses-certification' => 'Certificación y preparación de exámenes',
            'courses-coaching' => 'Programas de acompañamiento',
            'software-desktop' => 'Programas de escritorio',
            'software-mobile' => 'Aplicaciones móviles',
            'software-plugins' => 'Complementos y extensiones',
            'software-scripts' => 'Scripts y código',
            'software-saas' => 'Aplicaciones web y SaaS',
            'templates-themes' => 'Temas para webs',
            'templates-landing' => 'Páginas de destino',
            'templates-email' => 'Plantillas de correo',
            'templates-ui-kits' => 'Kits de interfaz y componentes',
            'graphics-illustrations' => 'Ilustraciones y vectores',
            'graphics-fonts' => 'Tipografías',
            'graphics-icons' => 'Iconos y logotipos',
            'graphics-motion' => 'Motion graphics y ajustes',
            'digital-documents' => 'Documentos, formularios y plantillas de empresa',
            'documents-contracts' => 'Contratos y formularios legales',
            'documents-spreadsheets' => 'Hojas de cálculo y calculadoras',
            'documents-presentations' => 'Presentaciones y dosieres',
            'documents-resumes' => 'Currículos y cartas de presentación',
            'documents-policies' => 'Políticas y procedimientos',
            'audio-music' => 'Pistas musicales',
            'audio-sfx' => 'Efectos de sonido',
            'audio-loops' => 'Loops y samples',
            'audio-spoken' => 'Pódcast y audiolibros',
            'digital-memberships' => 'Membresías y suscripciones digitales',
            'memberships-sites' => 'Sitios de membresía',
            'memberships-newsletters' => 'Boletines de pago',
            'memberships-communities' => 'Comunidades y grupos',
            'memberships-libraries' => 'Bibliotecas de contenido',
            'digital-licenses' => 'Licencias y claves de activación',
            'licenses-software' => 'Licencias de software',
            'licenses-game-keys' => 'Claves de juego',
            'licenses-gift-cards' => 'Tarjetas regalo y vales',
            'licenses-commercial' => 'Licencias de uso comercial',
            'digital-data-reports' => 'Datos, investigación e informes',
            'data-market-research' => 'Estudios de mercado',
            'data-datasets' => 'Conjuntos de datos',
            'data-industry-reports' => 'Informes sectoriales',
            'data-whitepapers' => 'Informes técnicos',
            'digital-ai-assets' => 'Prompts de IA y recursos de automatización',
            'ai-prompt-packs' => 'Packs de prompts',
            'ai-agents' => 'Asistentes y agentes personalizados',
            'ai-workflows' => 'Flujos de automatización',
            'ai-models' => 'Modelos y datos de entrenamiento',
            'digital-printables' => 'Productos imprimibles',
            'printables-planners' => 'Agendas y diarios',
            'printables-wall-art' => 'Láminas y pósteres',
            'printables-invitations' => 'Invitaciones y tarjetas',
            'printables-worksheets' => 'Fichas y actividades',
            'printables-patterns' => 'Patrones y archivos de corte',
            'digital-games' => 'Juegos y ocio digital',
            'games-indie' => 'Juegos independientes',
            'games-assets' => 'Recursos y mods para juegos',
            'games-tabletop' => 'Juegos de mesa e imprimibles',
            'games-virtual-items' => 'Objetos virtuales y aspectos',
            // Physical Products: the eighteen departments and their new leaves.
            'health-wellness' => 'Salud y bienestar',
            'medical-supplies' => 'Material sanitario',
            'first-aid' => 'Primeros auxilios',
            'home-appliances' => 'Electrodomésticos',
            'bath-body' => 'Baño y cuerpo',
            'grooming-shaving' => 'Aseo y afeitado',
            'baby-feeding' => 'Alimentación infantil',
            'tools-hardware' => 'Herramientas, ferretería y suministros industriales',
            'hardware-fasteners' => 'Ferretería y tornillería',
            'building-materials' => 'Materiales de construcción',
            'safety-workwear' => 'Seguridad y ropa de trabajo',
            'industrial-supplies' => 'Suministros industriales',
            'pet-health-products' => 'Salud y cuidado de mascotas',
            'sewing-textiles' => 'Costura y textiles',
            'fine-jewellery' => 'Alta joyería',
            'fashion-jewellery' => 'Bisutería',
            'watches' => 'Relojes',
            'wedding-engagement' => 'Boda y compromiso',
            'antiques' => 'Antigüedades',
            'trading-cards' => 'Cromos y cartas',
            'coins-stamps' => 'Monedas y sellos',
            'memorabilia' => 'Objetos de colección',
            'outdoor-cooking' => 'Barbacoas y cocina al aire libre',
            'local-products-gifts' => 'Productos locales y regalos',
            'gift-sets' => 'Cestas y sets de regalo',
            'local-artisan' => 'Artesanía local',
            'souvenirs' => 'Recuerdos y detalles',
            'seasonal-holiday' => 'Temporada y fiestas',
            'wholesale-business-supplies' => 'Venta al por mayor y suministros para empresas',
            'packaging-shipping' => 'Embalaje y envíos',
            'restaurant-supplies' => 'Hostelería y restauración',
            'retail-fixtures' => 'Mobiliario comercial',
            'pet-services' => 'Cuidado de niños, mayores y mascotas',
            // The seven markets, in the order the homepage grid shows them.
            'physical-products' => 'Productos físicos',
            'professional-services' => 'Servicios profesionales',
            'insurance' => 'Seguros',
            'insurance-auto' => 'Seguros de automóvil',
            'insurance-property' => 'Seguros de hogar y alquiler',
            'insurance-health' => 'Seguros de salud',
            'insurance-life' => 'Seguros de vida',
            'insurance-business' => 'Seguros de empresa y comercio',
            'insurance-travel' => 'Seguro de viaje',
            'insurance-pet' => 'Seguro para mascotas',
            'insurance-brokers' => 'Agentes y agencias de seguros',
            'travel' => 'Viajes',
            'travel-flights' => 'Vuelos',
            'travel-accommodation' => 'Hoteles y resorts',
            'travel-hotels' => 'Hoteles',
            'travel-vacation-rentals' => 'Alquileres vacacionales',
            'travel-hostels' => 'Albergues y casas de huéspedes',
            'travel-tours' => 'Tours y actividades',
            'travel-car-rental' => 'Alquiler de coches',
            'travel-cruises' => 'Cruceros',
            'travel-transport' => 'Traslados al aeropuerto',
            'travel-agents' => 'Agentes y asesores de viajes',
            'food-beverage' => 'Alimentación y comida especializada',
            'honey-pantry' => 'Miel y despensa',
            'raw-honey' => 'Miel cruda',
            'jams-preserves' => 'Mermeladas y conservas',
            'oils-vinegars' => 'Aceites y vinagres',
            'prepared-food' => 'Comida preparada',
            'baked-goods' => 'Panadería y repostería',
            'meal-prep' => 'Comidas preparadas',
            'coffee-tea' => 'Café y té',
            'beverages' => 'Bebidas',
            'snacks-confectionery' => 'Aperitivos y dulces',
            'specialty-diet' => 'Dietas especiales',
            'home-living' => 'Hogar, muebles y electrodomésticos',
            'kitchen-dining' => 'Cocina y mesa',
            'home-decor' => 'Decoración del hogar',
            'workshop-tools' => 'Taller y herramientas',
            'furniture' => 'Muebles',
            'bed-bath' => 'Dormitorio y baño',
            'storage-organisation' => 'Almacenaje y orden',
            'garden-outdoor' => 'Jardín y vida al aire libre',
            'plants-seeds' => 'Plantas y semillas',
            'garden-tools' => 'Herramientas de jardín',
            'outdoor-furniture' => 'Muebles de exterior',
            'cleaning-supplies' => 'Productos de limpieza',
            'local-services' => 'Hogar y local',
            'home-cleaning' => 'Limpieza',
            'trades-repair' => 'Fontanería, electricidad y climatización',
            'plumbing' => 'Fontanería',
            'electrical' => 'Electricidad',
            'carpentry' => 'Carpintería',
            'heating-cooling' => 'Climatización',
            'local-events' => 'Fotografía y servicios para eventos',
            'event-photography' => 'Fotografía de eventos',
            'event-catering' => 'Catering',
            'event-rentals' => 'Locales y alquiler',
            'moving-delivery' => 'Mudanzas y entregas',
            'lawn-landscaping' => 'Paisajismo y jardinería',
            'pest-control' => 'Control de plagas',
            'appliance-repair' => 'Reparación de electrodomésticos',
            'fashion-apparel' => 'Moda, calzado y accesorios',
            'bags-accessories' => 'Bolsos y accesorios',
            'womens-clothing' => 'Ropa de mujer',
            'mens-clothing' => 'Ropa de hombre',
            'footwear' => 'Calzado',
            'jewellery-watches' => 'Joyería y relojes',
            'vintage-secondhand' => 'Vintage y segunda mano',
            'electronics' => 'Electrónica e informática',
            'computers-accessories' => 'Informática y accesorios',
            'laptops' => 'Portátiles',
            'desktops' => 'Ordenadores de sobremesa',
            'peripherals' => 'Periféricos',
            'phones-tablets' => 'Móviles y tabletas',
            'audio-headphones' => 'Audio y auriculares',
            'cameras-photography' => 'Cámaras y fotografía',
            'smart-home' => 'Hogar inteligente',
            'gaming' => 'Videojuegos',
            'health-beauty' => 'Belleza y cuidado personal',
            'supplements' => 'Complementos alimenticios',
            'skincare' => 'Cuidado de la piel',
            'hair-care' => 'Cuidado del cabello',
            'cosmetics' => 'Cosmética',
            'fragrance' => 'Perfumeria',
            'wellness-fitness' => 'Bienestar y fitness',
            'personal-care-services' => 'Servicios de belleza y bienestar',
            'hair-barber' => 'Peluquería y barbería',
            'nails-spa' => 'Uñas y spa',
            'massage-therapy' => 'Masaje y terapia',
            'professionals' => 'Empresa y profesionales',
            'consulting' => 'Consultoría de empresas',
            'design-audit' => 'Diseño gráfico y creativo',
            'accounting-tax' => 'Contabilidad y teneduría de libros',
            'legal-services' => 'Servicios jurídicos',
            'marketing-advertising' => 'Marketing y publicidad',
            'web-development' => 'Desarrollo web y software',
            'writing-translation' => 'Redacción, traducción y apoyo administrativo',
            'education-tutoring' => 'Clases particulares y formación',
            'academic-tutoring' => 'Clases particulares',
            'music-lessons' => 'Clases de música',
            'language-lessons' => 'Clases de idiomas',
            'jobs' => 'Empleo',
            'job-listings' => 'Ofertas de empleo',
            'jobs-full-time' => 'Jornada completa',
            'jobs-part-time' => 'Media jornada',
            'jobs-contract' => 'Contrato y autónomos',
            'jobs-internships' => 'Prácticas',
            'jobs-volunteer' => 'Voluntariado',
            'digital-products' => 'Productos digitales',
            'digital-templates' => 'Plantillas y temas web',
            'digital-software' => 'Programas y aplicaciones',
            'digital-ebooks' => 'Libros electrónicos y publicaciones',
            'digital-courses' => 'Cursos en línea y material formativo',
            'digital-audio' => 'Música, efectos de sonido y medios digitales',
            'digital-graphics' => 'Gráficos, fotos, vídeo y audio',
            'digital-media' => 'Fotografía y vídeo de archivo',
            'sports-outdoors' => 'Deporte y aire libre',
            'fitness-equipment' => 'Equipamiento de fitness',
            'camping-hiking' => 'Camping y senderismo',
            'cycling' => 'Ciclismo',
            'water-sports' => 'Deportes acuáticos',
            'team-sports' => 'Deportes de equipo',
            'hunting-fishing' => 'Caza y pesca',
            'toys-kids-baby' => 'Bebés, niños y juguetes',
            'toys-games' => 'Juguetes y juegos',
            'baby-gear' => 'Artículos para bebés',
            'kids-clothing' => 'Ropa infantil',
            'school-supplies' => 'Material escolar',
            'childcare-services' => 'Cuidado infantil',
            'pets' => 'Artículos para mascotas',
            'pet-food' => 'Comida y premios',
            'pet-accessories' => 'Accesorios para mascotas',
            'pet-grooming' => 'Peluquería para mascotas',
            'pet-veterinary' => 'Veterinaria y salud animal',
            'pet-boarding' => 'Guardería y cuidado de mascotas',
            'automotive' => 'Automoción',
            'vehicles-for-sale' => 'Vehículos de ocasión',
            'auto-parts' => 'Piezas y accesorios para vehículos',
            'auto-repair' => 'Reparación y mantenimiento',
            'auto-detailing' => 'Limpieza y cuidado del vehículo',
            'tyres-wheels' => 'Neumáticos y llantas',
            'arts-crafts' => 'Arte, manualidades y hecho a mano',
            'handmade-art' => 'Arte hecho a mano',
            'craft-supplies' => 'Material de manualidades',
            'stationery-paper' => 'Papelería',
            'collectibles-antiques' => 'Coleccionismo',
            'books-media' => 'Libros y medios físicos',
            'books' => 'Libros',
            'music-vinyl' => 'Música y vinilos',
            'film-video' => 'Cine y vídeo',
            'magazines-comics' => 'Revistas y cómics',
            'real-estate' => 'Inmuebles',
            'property-for-sale' => 'Vivienda en venta',
            'property-for-rent' => 'Alquiler residencial',
            'property-commercial' => 'Inmuebles comerciales en venta',
            'property-rooms' => 'Habitaciones y pisos compartidos',
            'property-services' => 'Administración de fincas',
            'business-office' => 'Material de oficina y escolar',
            'office-supplies' => 'Material de oficina',
            'business-equipment' => 'Equipamiento profesional',
            'printing-signage' => 'Impresión y rotulación',
            'wholesale-bulk' => 'Venta al por mayor',
            'community' => 'Comunidad',
            'community-listings' => 'Anuncios de la comunidad',
            'community-classes' => 'Clases y talleres',
            'community-groups' => 'Grupos locales',
            'community-lost-found' => 'Objetos perdidos',
            'community-free' => 'Gratis y regalos',
        ]);

        $count += $this->translate(SocialPlatform::class, 'key', 'label', [
            'x' => 'X (Twitter)',
            'custom' => 'Enlace personalizado',
        ]);

        $count += $this->translate(PolicyType::class, 'key', 'label', [
            'shipping' => 'Política de envío',
            'return_refund' => 'Política de devoluciones y reembolsos',
            'cancellation' => 'Política de cancelación',
            'privacy' => 'Política de privacidad',
            'terms_and_conditions' => 'Términos y condiciones',
            'warranty' => 'Política de garantía',
            'custom' => 'Políticas personalizadas de la tienda',
        ]);

        $count += $this->translate(PolicyType::class, 'key', 'hint', [
            'shipping' => 'Detalles de entrega estándar y exprés',
            'return_refund' => 'Devoluciones en 30 días para artículos sin abrir',
            'cancellation' => 'Cómo y cuándo se pueden cancelar los pedidos',
            'privacy' => 'Cómo se recopilan y almacenan los datos del cliente',
            'terms_and_conditions' => 'Condiciones de servicio propias de la tienda',
            'warranty' => 'Condiciones de garantía de productos y servicios',
            'custom' => 'Políticas adicionales propias de su negocio',
        ]);

        $count += $this->translate(SettingDefinition::class, 'key', 'label', [
            'store_visibility' => 'Visibilidad de la tienda',
            'vacation_mode' => 'Modo vacaciones',
            'accept_new_orders' => 'Aceptar nuevos pedidos',
            'display_product_ratings' => 'Mostrar valoraciones de productos',
            'display_sales_count' => 'Mostrar número de ventas',
            'allow_customers_to_follow_the_store' => 'Permitir que los clientes sigan la tienda',
            'enable_customer_questions' => 'Habilitar preguntas de clientes',
            'show_social_links_publicly' => 'Mostrar enlaces sociales públicamente',
            'allow_customers_to_message_the_store' => 'Permitir que los clientes envíen mensajes',
            'display_customer_service_phone_number' => 'Mostrar el teléfono de atención al cliente',
            'min_order_amount' => 'Importe mínimo del pedido',
            'default_currency' => 'Moneda predeterminada',
            'default_language' => 'Idioma predeterminado',
            'store_timezone' => 'Zona horaria de la tienda',
        ]);

        $count += $this->translate(NotificationChannel::class, 'key', 'label', [
            'email' => 'Correo electrónico',
            'sms' => 'SMS',
            'push' => 'Notificaciones push',
            'in_app' => 'En la aplicación',
        ]);

        $count += $this->translate(NotificationTopic::class, 'key', 'label', [
            'order_updates' => 'Actualizaciones de pedidos',
            'delivery_notifications' => 'Notificaciones de entrega',
            'direct_messages' => 'Mensajes directos',
            'question_replies' => 'Respuestas a preguntas sobre productos',
            'review_reminders' => 'Recordatorios de valoración',
            'store_updates' => 'Novedades de tiendas seguidas',
            'price_alerts' => 'Alertas de bajada de precio y reposición',
            'promotions' => 'Cupones y promociones',
            'announcements' => 'Anuncios de AsBeez',
            'reward_updates' => 'Actualizaciones de recompensas y referidos',
            'security_alerts' => 'Alertas de seguridad e inicio de sesión',
        ]);

        $count += $this->translateNavGroups();

        $this->command?->info("Spanish content: {$count} translations stored.");
    }

    /**
     * @param  class-string  $model
     * @param  array<string, string>  $values
     */
    private function translate(string $model, string $key, string $field, array $values): int
    {
        $stored = 0;

        foreach ($values as $identifier => $translation) {
            $record = $model::where($key, $identifier)->first();

            if (! $record) {
                continue;
            }

            $record->setTranslation(self::LOCALE, $field, $translation);
            $stored++;
        }

        return $stored;
    }

    /**
     * Navigation group headings repeat across many links, so they are
     * translated by heading rather than row by row.
     */
    private function translateNavGroups(): int
    {
        $groups = [
            // Vendor workspace
            'Catalog' => 'Catálogo',
            'Sales' => 'Ventas',
            'Customers' => 'Clientes',
            'Marketing' => 'Marketing',
            'Analytics & Finance' => 'Analítica y finanzas',
            'Store Configuration' => 'Configuración de la tienda',
            'Account & Support' => 'Cuenta y soporte',
            // Member workspace
            'Profile and preferences' => 'Perfil y preferencias',
            'Shopping' => 'Compras',
            'Saved items' => 'Artículos guardados',
            'Communication' => 'Comunicación',
            'Reviews and community' => 'Valoraciones y comunidad',
            'Payments and financial activity' => 'Pagos y actividad financiera',
            'Rewards and referrals' => 'Recompensas y referidos',
            'Account settings and security' => 'Ajustes de cuenta y seguridad',
            'Help and support' => 'Ayuda y soporte',
        ];

        $stored = 0;

        foreach ($groups as $english => $spanish) {
            foreach (NavLink::where('group', $english)->get() as $link) {
                $link->setTranslation(self::LOCALE, 'group', $spanish);
                $stored++;
            }
        }

        return $stored;
    }
}
